image: mcr.microsoft.com/playwright:focal

stages:
  - test

test:
  stage: test
  script:
    - npm install
    - npx playwright install --with-deps
    - npx playwright test
  artifacts:
    when: always
    paths:
      - test-results/
      - playwright-report/
    reports:
      junit: test-results/junit.xml
